image: mcr.microsoft.com/dotnet/sdk:6.0  # .NET 6 SDK Docker image 

stages:
  - build
  - test

variables:
  BUILD_DIR: 'bin/Release'

# .NET Restore, Build, and Publish for UserService
build-user-service:
  stage: build
  script:
    - cd UserService
    - dotnet restore UserService.csproj
    - dotnet build UserService.csproj -c Release -o $BUILD_DIR
    - dotnet publish UserService.csproj -c Release -o $BUILD_DIR
  artifacts:
    paths:
      - UserService/$BUILD_DIR/**

# .NET Test for UserService
test-user-service:
  stage: test
  script:
    - cd UserService.Tests
    - dotnet restore UserService.Tests.csproj
    - dotnet test --no-restore

# .NET Restore, Build, and Publish for NotificationService
build-notification-service:
  stage: build
  script:
    - cd NotificationService
    - dotnet restore NotificationService.csproj
    - dotnet build NotificationService.csproj -c Release -o $BUILD_DIR
    - dotnet publish NotificationService.csproj -c Release -o $BUILD_DIR
  artifacts:
    paths:
      - NotificationService/$BUILD_DIR/**

# .NET Restore, Build, and Publish for BlogService
build-blog-service:
  stage: build
  script:
    - cd BlogService
    - dotnet restore BlogService.csproj
    - dotnet build BlogService.csproj -c Release -o $BUILD_DIR
    - dotnet publish BlogService.csproj -c Release -o $BUILD_DIR
  artifacts:
    paths:
      - BlogService/$BUILD_DIR/**

# .NET Test for BlogService
test-blog-service:
  stage: test
  script:
    - cd BlogService.Tests
    - dotnet restore BlogService.Tests.csproj
    - dotnet test --no-restore
