image: mcr.microsoft.com/dotnet/sdk:6.0  # .NET 6 SDK Docker image 

stages:
  - build
  - test
  - deploy

variables:
  PROJECT_NAME: 'UserService'
  BUILD_DIR: 'bin/Release'

# .NET Restore, Build, and Publish
build:
  stage: build
  script:
    - cd $PROJECT_NAME
    - dotnet restore $PROJECT_NAME.csproj
    - dotnet build $PROJECT_NAME.csproj -c Release -o $BUILD_DIR
    - dotnet publish $PROJECT_NAME.csproj -c Release -o $BUILD_DIR
  artifacts:
    paths:
      - $PROJECT_NAME/$BUILD_DIR/**

# .NET Test for UserService
test:
  stage: test
  script:
    - cd UserService.Tests
    - dotnet restore UserService.Tests.csproj
    - dotnet test --no-restore

# Deploy (You'd typically push your docker image to a registry, or deploy to a server)
deploy:
  stage: deploy
  script:
    - echo "Deployment step. Expand as needed."
    # Example:
    # docker build -t myregistry/userservice:$CI_COMMIT_SHORT_SHA $PROJECT_NAME
    # docker push myregistry/userservice:$CI_COMMIT_SHORT_SHA
