version: '3.8'

services:
  mongo:
    container_name: mongo_container
    image: mongo:latest
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  mssql:
    container_name: mssql_container
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword1!
    ports:
      - "1433:1433"

  postgres:
    container_name: postgres_container
    image: postgres:alpine3.18
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend-react-app:
    container_name: frontend_container
    image: frontend-react-app
    ports:
      - "3000:80"
    restart: no

  userservice:
    container_name: userservice_container
    image: userservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5108:80"
    working_dir: /app

  blogservice:
    container_name: blogservice_container
    image: blogservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5097:80"
    working_dir: /app
    
  notificationservice:
    container_name: notificationservice_container
    image: notificationservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5006:80"
    working_dir: /app

volumes:
  mongo-config:
  mongo-data:
  rabbitmq-data:
  postgres-data:
